language: python
python:
  - "2.7"
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest
  - python3 ipinfo/scripts/ipinfo_db_update.py
script:
  - pytest